name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_NAME: ${{ secrets.DOCKER_USERNAME  }}
        DOCKER_PWD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_NAME -p $DOCKER_PWD
    - name: Build the Fastapi Docker image
      run: |
        docker build . --file Dockerfile --tag fastapi-dockerize:1.0
    - name: docker push
      run: |
        echo "pushing the fastapi-dockerize image to docker registry"
        docker push 
