name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: echo hello
      run: echo "hello"
    - name: Build and Push Image To Docker registry 
      uses: mr-smithers-excellent/docker-build-push@v5.9
      with:
        image: shravankamble/fastapi-dockerize
        tags: v0.0.1
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
