name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  formatter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m pip install --upgrade pip
        pip install mypy
    - name: Formatting the code with isort
      run: |
        mypy main.py

  build:
    needs: formatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: echo hello
      run: echo "hello"
    - name: Build and Push Image To Docker registry 
      # To push our docker image to docker registry we are using below action to build the image and push it.
      uses: mr-smithers-excellent/docker-build-push@v5.9
      with:
        image: shravankamble/fastapi-dockerize
        tags: v0.0.2
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
